#!/bin/bash
# $1   kue job type
# $2   kue job title
# $3   kue job url [optional]

job="$1"
if [ "$1" == "" ]; then
	job="test"
fi

title="$2"

url="$3"
if [ "$3" == "" ]; then
	url=http://localhost:3000/job
fi

curl -H "Content-Type: application/json" -X POST -d \ "{ \"type\": \"${job}\", \"data\": { \"title\": \"${title}\" } }" ${url}
